# $Id: docker-compose.yml v.0.5 $ $Date: 2018/04/28 $ $Author: Filippo 'joeyrs' Civiletti <fc@xafe.it> $
# $Id: docker-compose.yml v.0.5 $ $Date: 2018/04/28 $ $Author: GB 'gionniboy' Pullarà <info@firegarden.co> $

# Docker-compose -- Build LEMP stack based on docker containers.

version: '3.7'

services:

  nginx:
    image: nginx:latest
    container_name: alpazzo-nginx
    environment:
      - TERM=xterm-256color
    links:
      - php7
    networks:
      - alpazzo
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./public:/var/www/html
    depends_on:
      - mariadb

  php7:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpazzo-php7
    environment:
      - TERM=xterm-256color
    networks:
      - alpazzo
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: alpazzo-mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "TERM=xterm-256color"
    networks:
      - alpazzo
    ports:
      - "3306:3306"
    restart: unless-stopped
    # volumes:
    #   - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mariadb

# Build diretives for Docker Network Bridging
networks:
  alpazzo:
